[package]
authors = ["Emirhan TALA <emirhantala99ff99@gmail.com>"]
name = "clock"
version = "0.1.2"
edition = "2021"


[dependencies]
chrono = "0.4.26"
clap = "2.34.0"


[target.'cfg(windows)'.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"


[target.'cfg(not(windows))'.dependencies]
libc = "0.2"